/*Autogenerated data file */
#include "htmlfiles.h"

const char * default_page="INDEX.HTM";

const unsigned char FilePointer0[]={
156, 62, 13, 10,138, 62, 13, 10, 84,104,101, 32,109, 97,105,
110, 32,112, 97,103,101, 32,102,111,114, 32,116,104,101, 32, 76,
 97, 98, 48, 32,112,114,111,106,101, 99,116, 46, 13, 10,202, 62,
 13, 10,220, 62, 13, 10,255,};


extern const HTML_FILE_RECORD file_record[1];

extern const unsigned  n_file_record;

const unsigned  n_file_record=1;

const HTML_FILE_RECORD file_record[1]={
{"index.htm",FilePointer0,54,eHuffmanHtml,eTypeHtml},
}; 


const int file_password_groups[2]={
0,-1}; 

extern const char *  html_table[];
const char *  html_table[64]={
"A","ADDRESS","APPLET","AREA",
"B","BASE","BASEFONT","BIG",
"BLINK","BLOCKQUOTE","BODY","BR",
"CAPTION","CENTER","CITE","CODE",
"DD","DIR","DL","DT",
"EM","FONT","FORM","FRAME",
"FRAMESET","HEAD","HN","HR",
"HTML","I","IMG","INPUT",
"ISINDEX","KBD","LI","LINK",
"MAP","MENU","META","NOBR",
"NOFRAMES","OL","OPTION","P",
"PARAM","PRE","SAMP","SCRIPT",
"SELECT","SMALL","STRONG","SUB",
"SUP","TABLE","TD","TEXTAREA",
"TH","TITLE","TR","TT",
"U","UL","VAR","" };


int DoHtmlFunction(int fd, PCSTR url,WORD n) { return 0; };

int DoHtmlVariable(int fd,WORD n) { return 0; };
